### ISSUE TITLE
KEYBOARD #011 Case files

### ISSUE THREAD

**Issue by ykz89** [hide-key/testamatta#6]
Hi!
I am interested in building KEYBOARD #011 with the cnc case.
Are you planning to publish the files to have the case made too?

**Comment by hide-key** [comment]
I do have some prototype data on hand, but I forgot to set up clearance with the PCB, so I think it might be best to make some modifications.

Also, aside from the bottom case, the design includes a white acrylic switch plate, so I'll need that data as well. However, I don’t quite understand the mechanism of the stabilizers, so with the current switch plate data, it's not possible to attach the stabilizers. Additionally, I made a mistake in designing the switch plate; it should have been 1.5mm thick to accommodate the stabilizers, but I designed it to be 2mm thick.

I can prepare the STEP data that addresses both issues: modifying the clearance of the bottom case and removing the unnecessary holes in the stabilizer part of the 2mm thick switch plate. I’ll need a little time to make these modifications. Would that be alright with you?

**Comment by ykz89** [comment]
Yes of course, take your time.
Thank you

**Comment by hide-key** [comment]
I've prepared the data you requested. It includes the STEP data (for the bottom case and switch plate), PDF data (showing the screw hole locations), and DXF data (2D version of the switch plate). If there's anything unclear, just let me know.

**Comment by ykz89** [comment]
That was fast!
I'll check it out, thanks!

**Comment by ykz89** [comment]
I tried ordering the PCB from JLCPCB, but they are giving me the message:
> Audit failure reason:
> 1.here is no Gerber file in your zip file, could you please kindly check it?
Do you have an idea what could be wrong?

**Comment by ykz89** [comment]
> I tried ordering the PCB from JLCPCB, but they are giving me the message:
> 
> > Audit failure reason:
> > 1.here is no Gerber file in your zip file, could you please kindly check it?
> > Do you have an idea what could be wrong?

It seemed to be a mistake on their side. No issue here!

**Comment by ykz89** [comment]
They are giving me another reason now:
> Failure Reason:
There is only drill layer in your gerber file, can you check?

Can you check if that's correct?

**Comment by hide-key** [comment]
I have been able to upload the same data and add it to the cart without any issues. Also, as far as I can see from the contents of the Zip file, all the data necessary for the Gerber file is included. Please take a moment to check the contents of the Zip file yourself. If you are using Windows, you can directly inspect the Zip file, and if you are on Mac, you should be able to see the contents by unzipping it.

**Comment by ykz89** [comment]
This was after I placed the order and paid, but I'll try again.

**Comment by hide-key** [comment]
If needed, I can provide the data in uncompressed form.

**Comment by ykz89** [comment]
![PXL_20231017_223844789](https://github.com/hide-key/testamatta/assets/4377149/74b23ce1-5e2f-4cb7-9092-b1a3c19db067)
I received the cnc case, I'm just waiting for the switch plate to finish it!

Just a question: would it be doable to split the 2x2u keys into 4x1u?

**Comment by ykz89** [comment]
Thank you.
Everyone I showed this picture to wanted a version with more thumb keys 😄 

I switched to using [minimelf](https://eu.mouser.com/new/vishay/vishay-semi-minimelf-diodes/) diodes because of the looks. I think they look nicer than the black SMD diodes

**Comment by hide-key** [comment]
Oops!? I just learned about minimelf diodes for the first time. That's a good choice.
I've immediately redesigned the PCB to the 1u x 4 version.
[](https://github.com/hide-key/testamatta/tree/main/keyboard/pcb/011/rev2)
However, I completely forgot that I have to recreate the firmware.
It's past midnight in Japan time, so I'll try to proceed with recreating the firmware sometime tomorrow or later.

**Comment by hide-key** [comment]
Oops!? I just learned about minimelf diodes for the first time. That's a good choice.
I've immediately redesigned the PCB to the 1u x 4 version.
[https://github.com/hide-key/testamatta/tree/main/keyboard/pcb/011/rev2](https://github.com/hide-key/testamatta/tree/main/keyboard/pcb/011/rev2)
However, I completely forgot that I have to recreate the firmware.
It's past midnight in Japan time, so I'll try to proceed with recreating the firmware sometime tomorrow or later.

**Comment by ykz89** [comment]
Wow that was fast 😄
Take your time, oyasumi!

**Comment by hide-key** [comment]
For now, I've also created firmware for the change from '2U x 2' to '1U x 4'. However, since there's no PCB, I only installed it on XIAO. I think it's probably fine though.
![image](https://github.com/hide-key/testamatta/assets/94853324/440caa4e-083e-44a8-a3e0-95417af221e1)

**Comment by ykz89** [comment]
Thank you so much 
I have ordered the PCB.
Could I ask you to also alter the switch plate? But no hurry, since it will take a few weeks before the PCBs will arrive.

**Comment by hide-key** [comment]
Just to let you know, I've quickly uploaded the switch plate (011_switch_plate_rev2.dxf) at:
[Just to let you know, I've quickly uploaded the switch plate (011_switch_plate_rev2.dxf) at:
https://github.com/hide-key/testamatta/tree/main/keyboard/dxf.](https://github.com/hide-key/testamatta/tree/main/keyboard/dxf).

**Comment by ykz89** [comment]
Thank you!
Just to let you know, the rev1 switch plate doesn't have holes for stabilizers. I didn't use them with [my build](https://x.com/yingkun/status/1717170531076596217), so it's no problem for me.
